version: '3.3'
services:
  api:
    image: bambo0st/backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://adithya:adithya123@cabpoolcluster.2vzp6.mongodb.net/
      - JWT_SECRET=THIS IS THE SECRET
    depends_on:
      - mongodb
    networks:
      - cab-pool-network

  client:
    image: bambo0st/frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:3000
      # I am not defining VITE_API_URL in env file, only in docker-compose environment
    networks:
      - cab-pool-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "23017:27017"
    networks:
      - cab-pool-network

networks:
  cab-pool-network:
    driver: bridge
