# version: '3.5'

services:
  api:
    image: Bambo0st/backend:latest
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb+srv://adithya:adithya123@cabpoolcluster.2vzp6.mongodb.net/
      - JWT_SECRET=THIS IS THE SECRET
    depends_on:
      - mongodb
    networks:
      - cab-pool-network

  client:
    image: Bambo0st/frontend:latest
    ports:
      - "5173:5173"
    networks:
      - cab-pool-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "23017:23017"
    networks:
      - cab-pool-network

networks:
  cab-pool-network:
    driver: bridge
