---
- name: Deploying with Kubernetes
  hosts: all
  tasks:

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 

    - name: Apply Secrets
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/cabpool-secrets.yaml') | from_yaml }}"

    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/frontend-deployment.yaml') | from_yaml }}" 

    - name: Create Frontend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/frontend-service.yaml') | from_yaml }}" 


    - name: Create Backend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/backend-deployment.yaml') | from_yaml }}"

    - name: Create Backend Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/backend-service.yaml') | from_yaml }}"

    - name: Create Ingress
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './k8s/mern-ingress.yaml') | from_yaml }}" 