---
- name: Deploy Docker Containers with Docker Compose
  hosts: localhosts
  tasks:

    - name: Ensure /opt/cabpool directory exists
      file:
        path: /opt/cabpool
        state: directory
        mode: '0755'

    - name: Ensure Docker Compose is installed
      package:
        name: docker-compose
        state: present

    - name: Copy docker-compose.yml to remote server
      copy:
        src: ./docker-compose.yml
        dest: /opt/cabpool/docker-compose.yml

    - name: Pull Docker images with Docker Compose
      command: docker-compose -f /opt/cabpool/docker-compose.yml pull

    - name: Start the containers using Docker Compose
      command: docker-compose -f /opt/cabpool/docker-compose.yml up -d
