---
- name: Deploy Docker Containers with Docker Compose
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  become: true
  tasks:
    - name: Pull Docker image
      docker_image:
        name: bambo0st/calculator:latest
        source: pull
    # - name: Copy docker-compose.yml to remote server
    #   copy:
    #     src: ./docker-compose.yml
    #     dest: docker-compose.yml

    # - name: Pull Docker images with Docker Compose
    #   command: docker-compose -f docker-compose.yml pull

    # - name: Start the containers using Docker Compose
    #   command: docker-compose -f docker-compose.yml up -d
