apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabpool-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cabpool-backend
  template:
    metadata:
      labels:
        app: cabpool-backend
    spec:
      containers:
        - name: backend
          image: bambo0st/backend:latest 
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: cabpool-secrets
                  key: mongo_url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cabpool-secrets
                  key: jwt_secret
